/** @jsxImportSource @emotion/react */
import React from 'react'
import { css } from '@emotion/react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    // eslint-disable-next-line react/react-in-jsx-scope
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello to Ultimate project audience</h1>
        <div
          css={css`
            font-size: 20px;
            color: white;
            background-color: blue;
            padding: 32px;
            border-radius: 5px;
          `}
        >
          This section has emotion ;/
        </div>
      </main>
    </div>
  )
}
